package MiB;

import AdminVy.AdminVy;
import AgentVy.AgentVy;
import AlienVy.AlienVy;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author calle
 */
public class InloggSidan extends javax.swing.JFrame {

    private static InfDB idb;

    public InloggSidan(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAlienID = new javax.swing.JTextField();
        txtAgentID = new javax.swing.JTextField();
        btnLogInAgent = new javax.swing.JButton();
        btnLogInAlien = new javax.swing.JButton();
        JpassAgentLösen = new javax.swing.JPasswordField();
        JpassAlienLösen = new javax.swing.JPasswordField();
        lblAgentID = new javax.swing.JLabel();
        lblAgentLösen = new javax.swing.JLabel();
        lblAlienID = new javax.swing.JLabel();
        lblAlienLösen = new javax.swing.JLabel();
        lblAgentLogo = new javax.swing.JLabel();
        lblAlienLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAgentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgentIDActionPerformed(evt);
            }
        });

        btnLogInAgent.setText("Logga in");
        btnLogInAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInAgentActionPerformed(evt);
            }
        });

        btnLogInAlien.setText("Logga in");
        btnLogInAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInAlienActionPerformed(evt);
            }
        });

        JpassAgentLösen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JpassAgentLösenActionPerformed(evt);
            }
        });

        lblAgentID.setText("Agent-ID");

        lblAgentLösen.setText("Lösenord");

        lblAlienID.setText("Alien-ID");

        lblAlienLösen.setText("Lösenord");

        lblAgentLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MiB/Agent vektor.png"))); // NOI18N

        lblAlienLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MiB/alien vektor ny.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblAgentID)))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblAgentLösen))
                            .addComponent(JpassAgentLösen, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnLogInAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblAgentLogo)))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogInAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlienLösen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JpassAlienLösen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblAlienLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAlienLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlienLösen))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JpassAlienLösen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnLogInAlien))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAgentLogo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgentLösen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAgentID, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JpassAgentLösen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnLogInAgent)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInAgentActionPerformed

        if (Validering.tomtTextFält(txtAgentID) && Validering.tomtTextFält(JpassAgentLösen) && Validering.kollaHeltal(txtAgentID)) {
            String id = txtAgentID.getText();
            String lösenord = JpassAgentLösen.getText();

            try {
                String login = idb.fetchSingle("SELECT losenord FROM AGENT where AGENT_ID =" + id);
                String admin = idb.fetchSingle("SELECT administrator FROM AGENT where AGENT_ID=" + id);

                if (admin.equals("J")) {

                    if (lösenord.equals(login)) {
                        AdminVy adminvy = new AdminVy(idb);
                        adminvy.setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Fel användarnamn eller lösenord");
                    }

                } else if (lösenord.equals(login)) {
                    AgentVy agentvy = new AgentVy(idb);
                    agentvy.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Fel användarnamn eller lösenord");
                }

            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Någonting gick fel!");
                System.out.println("Internt felmeddelande " + e.getMessage());
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Något gick fel!");
                System.out.println("Internt felmeddelande " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnLogInAgentActionPerformed

    private void txtAgentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgentIDActionPerformed
        if (Validering.tomtTextFält(txtAgentID) && Validering.tomtTextFält(JpassAgentLösen) && Validering.kollaHeltal(txtAgentID)) {
            String id = txtAgentID.getText();
            String lösenord = JpassAgentLösen.getText();

            try {
                String login = idb.fetchSingle("SELECT losenord FROM AGENT where AGENT_ID =" + id);
                String admin = idb.fetchSingle("SELECT administrator FROM AGENT where AGENT_ID=" + id);

                if (admin.equals("J")) {

                    if (lösenord.equals(login)) {
                        AdminVy adminvy = new AdminVy(idb);
                        adminvy.setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Fel användarnamn eller lösenord");
                    }

                } else if (lösenord.equals(login)) {
                    AgentVy agentvy = new AgentVy(idb);
                    agentvy.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Fel användarnamn eller lösenord");
                }

            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Någonting gick fel!");
                System.out.println("Internt felmeddelande " + e.getMessage());
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Något gick fel!");
                System.out.println("Internt felmeddelande " + e.getMessage());
            }
        }

    }//GEN-LAST:event_txtAgentIDActionPerformed

    private void JpassAgentLösenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JpassAgentLösenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JpassAgentLösenActionPerformed

    private void btnLogInAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInAlienActionPerformed
        if (Validering.tomtTextFält(txtAlienID) && Validering.tomtTextFält(JpassAlienLösen) && Validering.kollaHeltal(txtAlienID)) {
            String id = txtAlienID.getText();
            String lösenord = JpassAlienLösen.getText();
            try {
                String login = idb.fetchSingle("SELECT losenord FROM ALIEN where ALIEN_ID =" + id);
                if (lösenord.equals(login)) {
                    AlienVy alienvy = new AlienVy(idb);
                    alienvy.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Fel användarnamn eller lösenord");

                }
            } catch (InfException e) {
               JOptionPane.showMessageDialog(null, "Ett fel har inträffat!");
               System.out.println("Internt felmeddelande: " + e.getMessage());

            }
        }
    }//GEN-LAST:event_btnLogInAlienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InloggSidan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InloggSidan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InloggSidan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InloggSidan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InloggSidan(idb).setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JpassAgentLösen;
    private javax.swing.JPasswordField JpassAlienLösen;
    private javax.swing.JButton btnLogInAgent;
    private javax.swing.JButton btnLogInAlien;
    private javax.swing.JLabel lblAgentID;
    private javax.swing.JLabel lblAgentLogo;
    private javax.swing.JLabel lblAgentLösen;
    private javax.swing.JLabel lblAlienID;
    private javax.swing.JLabel lblAlienLogo;
    private javax.swing.JLabel lblAlienLösen;
    private javax.swing.JTextField txtAgentID;
    private javax.swing.JTextField txtAlienID;
    // End of variables declaration//GEN-END:variables
}
