/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminVy;

import MiB.Validering;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author calle
 */
public class AdminÄndraAlienLösen extends javax.swing.JFrame {
private static InfDB idb;
    /**
     * Creates new form AdminÄndraAlienLösen
     */
    public AdminÄndraAlienLösen(InfDB idb) {
        initComponents();
         this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAlienID = new javax.swing.JLabel();
        txtAlienID = new javax.swing.JTextField();
        lblNyttLösenord = new javax.swing.JLabel();
        passNyttLösenord = new javax.swing.JPasswordField();
        btnÄndraLösenord = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        lblNuvarandeLösen = new javax.swing.JLabel();
        lblRubrik = new javax.swing.JLabel();
        passGammaltLösenord = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAlienID.setText("            Alien-ID");

        txtAlienID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlienIDActionPerformed(evt);
            }
        });

        lblNyttLösenord.setText("       Nytt Lösenord");

        passNyttLösenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passNyttLösenordActionPerformed(evt);
            }
        });

        btnÄndraLösenord.setText("Ändra Lösenord");
        btnÄndraLösenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraLösenordActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        lblNuvarandeLösen.setText("  Nuvarande lösenord");

        lblRubrik.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRubrik.setText("     Ändra Alien");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("      Lösenord");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnÄndraLösenord))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(passGammaltLösenord, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAlienID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNyttLösenord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNuvarandeLösen, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(passNyttLösenord)
                                .addComponent(txtAlienID))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblRubrik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblNuvarandeLösen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passGammaltLösenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNyttLösenord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passNyttLösenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnÄndraLösenord)
                .addGap(29, 29, 29)
                .addComponent(btnTillbaka)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAlienIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlienIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlienIDActionPerformed

    private void passNyttLösenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passNyttLösenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passNyttLösenordActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AdminHanteraAlien(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnÄndraLösenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraLösenordActionPerformed
        
            //Säkerställer att inga textfält är tomma.
        if (Validering.tommaTextFält(txtAlienID, passGammaltLösenord, passNyttLösenord)) {
            
            //Skapar lokalvariabler för ifyllt aliennamn, gammalt lösenord & nytt lösenord.
            String alien = txtAlienID.getText();
            String gammaltlösen = passGammaltLösenord.getText();
            String nyttlösen = passNyttLösenord.getText();
             

            try {
                String alienid = idb.fetchSingle("SELECT ALIEN_ID FROM ALIEN WHERE ALIEN_ID = " + alien);
                String lösenord = idb.fetchSingle("SELECT LOSENORD FROM ALIEN WHERE ALIEN_ID = " + alien);
                String aliennamn = idb.fetchSingle("SELECT NAMN FROM ALIEN WHERE ALIEN_ID = " + alien);
                         
                if(alien.equals(alienid) && gammaltlösen.equals(lösenord)){
                    idb.update("UPDATE ALIEN SET LOSENORD =" + "'" + nyttlösen + "'" + "WHERE ALIEN_ID =" + alien );
                    JOptionPane.showMessageDialog(null, "Du har ändrat " + aliennamn + "s lösenord!");
                    new AdminÄndraAlienLösen(idb).setVisible(true);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Användarnamn eller lösenord matchade inte, vänligen försök igen!");
                }
               

            } catch (InfException error) {
                System.out.println("Internt felmeddelande" + error.getMessage());

            }
        }
    
    }//GEN-LAST:event_btnÄndraLösenordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminÄndraAlienLösen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminÄndraAlienLösen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminÄndraAlienLösen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminÄndraAlienLösen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminÄndraAlienLösen(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnÄndraLösenord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAlienID;
    private javax.swing.JLabel lblNuvarandeLösen;
    private javax.swing.JLabel lblNyttLösenord;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JPasswordField passGammaltLösenord;
    private javax.swing.JPasswordField passNyttLösenord;
    private javax.swing.JTextField txtAlienID;
    // End of variables declaration//GEN-END:variables
}
