/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminVy;

import MiB.ComboBoxes;
import MiB.Validering;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author calle
 */
public class AdminLäggTillAgent extends javax.swing.JFrame {
private static InfDB idb;
    /**
     * Creates new form LäggTillAgentAdmin
     */
    public AdminLäggTillAgent(InfDB idb) {
        initComponents();
        this.idb = idb;
        cboxOmrådeschef.setVisible(true);
        
             
        //lokalvariabel combobox 
        ComboBoxes combobox = new ComboBoxes(idb);
        //Metodanrop till klassen Combobox, fyller cBoxOmråde med områden.
        combobox.fyllOmråde(cboxOmrade);
        cboxOmrade.setSelectedIndex(-1);
        //Gör att vid första anblick så är comboboxen tom & inte visar första området från databasen.
        //cboxOmrade.setSelectedIndex(-1);
        
        combobox.fyllOmråde(cboxOmrådeschef);
       cboxOmrådeschef.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblAnställningsdatum = new javax.swing.JLabel();
        lblTelefonNummer = new javax.swing.JLabel();
        lblLösenord = new javax.swing.JLabel();
        lblDatumForm = new javax.swing.JLabel();
        lblFältagent = new javax.swing.JLabel();
        lblAdministratör = new javax.swing.JLabel();
        lblKontorschef = new javax.swing.JLabel();
        txtNamn = new javax.swing.JTextField();
        txtAnställningsdatum = new javax.swing.JTextField();
        txtTelefonNummer = new javax.swing.JTextField();
        rbtnFältagent = new javax.swing.JRadioButton();
        rbtnAdministratör = new javax.swing.JRadioButton();
        rbtnKontorsChef = new javax.swing.JRadioButton();
        lblOmrådesChef = new javax.swing.JLabel();
        rbtnOmrådesChef = new javax.swing.JRadioButton();
        lblOmråde = new javax.swing.JLabel();
        cboxOmrade = new javax.swing.JComboBox<>();
        btnTillbaka = new javax.swing.JButton();
        btnLäggTillAgent = new javax.swing.JButton();
        jPassLösenord = new javax.swing.JPasswordField();
        cboxOmrådeschef = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrik.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRubrik.setText("Lägg till Ny Agent");

        lblNamn.setText("Namn");

        lblAnställningsdatum.setText("Anställningdatum");

        lblTelefonNummer.setText("Telefonnummer");

        lblLösenord.setText("Lösenord");

        lblDatumForm.setText("yy-mm-dd");

        lblFältagent.setText("Fältagent");

        lblAdministratör.setText("Administratör");

        lblKontorschef.setText("Kontorschef");

        lblOmrådesChef.setText("Områdeschef");

        lblOmråde.setText("Område");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnLäggTillAgent.setText("Lägg till Agent");
        btnLäggTillAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLäggTillAgentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFältagent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOmrådesChef, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAdministratör, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblKontorschef, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnKontorsChef)
                                    .addComponent(rbtnAdministratör)
                                    .addComponent(rbtnOmrådesChef)
                                    .addComponent(rbtnFältagent))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(cboxOmrådeschef, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatumForm)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAnställningsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLösenord, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefonNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNamn, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(txtTelefonNummer)
                                    .addComponent(jPassLösenord)
                                    .addComponent(txtAnställningsdatum)
                                    .addComponent(cboxOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblOmråde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLäggTillAgent)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblRubrik)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonNummer)
                    .addComponent(txtTelefonNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLösenord)
                    .addComponent(jPassLösenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnställningsdatum)
                    .addComponent(txtAnställningsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(lblDatumForm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOmråde)
                    .addComponent(cboxOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnOmrådesChef)
                            .addComponent(lblOmrådesChef))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFältagent)
                            .addComponent(rbtnFältagent))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdministratör)
                            .addComponent(rbtnAdministratör))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKontorschef, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnKontorsChef, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTillbaka)
                            .addComponent(btnLäggTillAgent)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(cboxOmrådeschef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AdminHanteraAgent(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnLäggTillAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLäggTillAgentActionPerformed
       //Säkerställer att valda text & lösenordsrutor inte är tomma. 
        if(Validering.tommaTextFält(txtAnställningsdatum, jPassLösenord, txtNamn, txtTelefonNummer) && Validering.kollaHeltal(txtTelefonNummer) ){
        //Skapar lokalvariabler för värdet på samtliga ifyllda text & Jpass fält
                String namn = txtNamn.getText();
                String tele = txtTelefonNummer.getText();
                String lösen = jPassLösenord.getText();
                String anstdatum = txtAnställningsdatum.getText();
                String admin = "";
                
//FUNKAR INTE ÄN
                try {
               
                

                //Skapar lokalvariabel för värdet på combobox för område.
                //String omrade = cboxOmrade.getSelectedItem().toString();
                
                //Genererar ett nytt agentID genom AutoIncrement som tar det högsta värdet i tabellen Agent kolumnen Agent_ID och adderar 1. Gör sedan om från sträng till int.
                String nyttID = idb.getAutoIncrement("AGENT", "AGENT_ID");
                int nyaID = Integer.parseInt(nyttID);
                
               

                //Omvandlar områdets sträng-värde från benämningen till dess ID & gör strängen till ett int-värde
                String omradesid = idb.fetchSingle("SELECT OMRADES_ID FROM OMRADE WHERE BENAMNING = " + "'" + cboxOmrade.getSelectedItem().toString() + "'"); //ÄNDRAT
                int omrID = Integer.parseInt(omradesid);

                //Om admin-knapp är ikryssad sätts lokalvariabeln admin som är deklarerad ovan till J, annars N.
                if (rbtnAdministratör.isSelected()) {
                    admin = "J";
                } else {
                    admin = "N";
                }

                //Om kontorschef-knapp är ikryssad sätts nya agent-ID in i tabellen för kontorschef. 
                if (rbtnKontorsChef.isSelected()){
                    idb.update("UPDATE KONTORSCHEF SET AGENT_ID = " + "'" + nyaID + "'");
                }
                
                //Om fältagent-knapp är ikryssad sätts nya agent-ID in i tabellen för fältagent
                if (rbtnFältagent.isSelected()){
                    idb.insert("INSERT INTO FALTAGENT SET AGENT_ID = " + "'" + nyaID + "'");
                }
                
                 //Skapar lokalvariabel för värdet på combobox för valt områdesansvar för områdeschef
                String omrchef = idb.fetchSingle("SELECT OMRADES_ID FROM OMRADE WHERE BENAMNING = " + "'" + cboxOmrådeschef.getSelectedItem().toString() + "'");
                int OmrChefOmr = Integer.parseInt(omrchef);
                
                //Om områdeschefs-knapp är ikryssad visas comboboxen för vilket område denna ska vara chef för.
                if (rbtnOmrådesChef.isSelected()){
                    //cboxOmrådeschef.setVisible(true);
                    //Sätter in områdeschef för nya agent-ID och valt område från comboboxen.
                    idb.insert("INSERT INTO OMRADESCHEF SET AGENT_ID = " + "'" + nyaID + "'" + OmrChefOmr + "'");
                }
                else{
                    cboxOmrådeschef.setVisible(false);
                }
                               
                //Sätter in angivna värden i db för Agent. 
                String nyAgent = "insert into agent values ('" +  nyaID + "'" + namn + ", '" + tele + ", '" + anstdatum + ", '" + admin +  "', " + lösen + "', " + omrID +"')";
                 
                idb.insert(nyAgent); 

                
                //Meddelande att try-frasen fungerat.
                JOptionPane.showMessageDialog(null, "Ny agent har registrerats! Välkommen " + namn + " ditt nya ID är: "  + ". Ditt lösenord är " + lösen);
            } catch (InfException error) {
                JOptionPane.showMessageDialog(null, "Ett fel uppstod, vänligen försök igen!");
                System.out.println("Internfel: " + error.getMessage());

            }catch (NumberFormatException error2){
                 JOptionPane.showMessageDialog(null, "Ett fel uppstod");
                System.out.println("Internfelet: " + error2.getMessage());
            }catch (NullPointerException error3){
                 JOptionPane.showMessageDialog(null, "Ett fel uppstod");
                System.out.println("Internfelet: " + error3.getMessage());  
                
            
                //Numberformatexception på combobox för områdeschef
                //input string blir null på combobox för område
        }
        }
    }//GEN-LAST:event_btnLäggTillAgentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLäggTillAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLäggTillAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLäggTillAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLäggTillAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLäggTillAgent(idb).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLäggTillAgent;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cboxOmrade;
    private javax.swing.JComboBox<String> cboxOmrådeschef;
    private javax.swing.JPasswordField jPassLösenord;
    private javax.swing.JLabel lblAdministratör;
    private javax.swing.JLabel lblAnställningsdatum;
    private javax.swing.JLabel lblDatumForm;
    private javax.swing.JLabel lblFältagent;
    private javax.swing.JLabel lblKontorschef;
    private javax.swing.JLabel lblLösenord;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblOmråde;
    private javax.swing.JLabel lblOmrådesChef;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblTelefonNummer;
    private javax.swing.JRadioButton rbtnAdministratör;
    private javax.swing.JRadioButton rbtnFältagent;
    private javax.swing.JRadioButton rbtnKontorsChef;
    private javax.swing.JRadioButton rbtnOmrådesChef;
    private javax.swing.JTextField txtAnställningsdatum;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtTelefonNummer;
    // End of variables declaration//GEN-END:variables
}
